# Generated by Django 5.2.3 on 2025-06-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, help_text='Fecha opcional en la que la tarea debería estar completada.', null=True, verbose_name='Fecha Límite'),
        ),
    ]
