# Generated by Django 5.2.3 on 2025-06-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('POSTED', 'Publicado'), ('IN_PROGRESS', 'En Progreso'), ('COMPLETED', 'Completado'), ('PAID', 'Pagado'), ('CANCELLED', 'Cancelado')], db_index=True, default='POSTED', max_length=20, verbose_name='Estado'),
        ),
    ]
