# Generated by Django 5.2.3 on 2025-07-05 19:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='owner_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comentario del propietario'),
        ),
        migrations.AddField(
            model_name='task',
            name='owner_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Calificación del propietario'),
        ),
    ]
